models/LegalService.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "legal_service".
 *
 * @property integer $id
 * @property integer $number
 * @property string $data_time
 * @property string $event
 * @property string $result
 */
class LegalService extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'legal_service';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['number'], 'integer'],
            [['data_time'], 'safe'],
            [['data_time', 'event','result'], 'required'],
            [['event', 'result'], 'string', 'max' => 2000],
            ['proc_id', 'integer'],
            
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('LegalService', 'ID'),
            'number' => Yii::t('LegalService', 'Number'),
            'data_time' => Yii::t('LegalService', 'Data Time'),
            'event' => Yii::t('LegalService', 'Event'),
            'result' => Yii::t('LegalService', 'Result'),
        ];
    }
    
    /**
    * get maximum serial number
    */
    public function getMaxNumber()
    {
        return $this->find()->select('max(number)')->where(['proc_id' => Yii::$app->session->get('current_proc_id')])->scalar();
    }
    
    public function beforeValidate()
    {
        if ($this->data_time != null) {
            $new_date_format = date('Y-m-d', strtotime($this->data_time));
            $this->data_time = $new_date_format;
        }
        
        return parent::beforeValidate();
    }
}

controllers/LegalServiceController.php
<?php

namespace app\controllers;

use Yii;
use app\models\LegalService;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * LegalServiceController implements the CRUD actions for LegalService model.
 */
class LegalServiceController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        //'actions' => ['index', 'error'],
                        'allow' => true,
                        'roles' => ['manager', 'backOffice', 'lawyer'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all LegalService models.
     * @return mixed
     */
    public function actionIndex()
    {
        $totalCount = Yii::$app->db->createCommand('SELECT COUNT(*) FROM ' . LegalService::tableName() . ' WHERE proc_id = :proc_id', [':proc_id' => Yii::$app->session->get('current_proc_id')])->queryScalar();

        $dataProvider = new ActiveDataProvider([
            'query' => LegalService::find()->where(['proc_id' => Yii::$app->session->get('current_proc_id')]),
            'totalCount' => (int)$totalCount,
            'pagination' => [
                // количество пунктов на странице
                'pageSize' => 20,
            ]
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single LegalService model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new LegalService model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new LegalService();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']); //return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing LegalService model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']); //return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing LegalService model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the LegalService model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return LegalService the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = LegalService::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/legal-service/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
//use yii\jui\DatePicker;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\LegalService */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="legal-service-form">
    <div class="row">
        <?php $form = ActiveForm::begin(); ?>
        <!--input type="hidden" id="legalservice-id" class="form-control" name="LegalService[id]" value="<?= ( $model->isNewRecord ? 0 : $model->id ) ?>"-->
        <input type="hidden" id="legalservice-proc_id" class="form-control" name="LegalService[proc_id]" value="<?= Yii::$app->session->get('current_proc_id') ?>">
        <div class="row">
            <div class="col-xs-12">
                <div class="col-xs-4">
                    <?= $form->field($model, 'number')->textInput(['type' => 'number', 'value' => ( $model->number ? $model->number : $model->maxNumber + 1)]) ?>
                </div>
            </div>
        </div>
        <div class="col-xs-4">
            <?=
            $form->field($model, 'data_time')->textInput()->widget(DatePicker::classname(), [
                'language' => 'ru',
                'options' => ['value' => ( $model->data_time ? date('d.m.Y', strtotime($model->data_time)) : date('d.m.Y') )],
                'pluginOptions' => [
                    'autoclose' => true,
                    'format' => 'dd.mm.yyyy'
                ]
                /*
                'language' => 'ru',
                'dateFormat' => 'yyyy-MM-dd',
                'options' => ['class' => 'form-control', 'required' => true,],
                
                'name' => 'check_issue_date',
                'value' => date('d-M-Y', strtotime('+2 days')),
                'options' => ['placeholder' => 'Select issue date ...'],
                'pluginOptions' => [
                    'format' => 'dd-M-yyyy',
                    'todayHighlight' => true
                ]*/
            ])
            ?> 
        </div>
        <div class="col-xs-12">
<?= $form->field($model, 'event')->textarea(['maxlength' => true, 'rows' => 7, 'required' => true]) ?>
        </div>
        <div class="col-xs-12">
<?= $form->field($model, 'result')->textarea(['maxlength' => true, 'rows' => 7, 'required' => true]) ?>
        </div>
        <div class="col-xs-12 form-group">
<?= Html::submitButton($model->isNewRecord ? Yii::t('LegalService', 'Create') : Yii::t('LegalService', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>

<?php ActiveForm::end(); ?>
    </div>
</div>

views/legal-service/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\LegalService */

$this->title = Yii::t('LegalService', 'Create record');
$this->params['breadcrumbs'][] = ['label' => Yii::t('LegalService', 'Legal Services'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="legal-service-create">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/legal-service/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('LegalService', 'Legal Services');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="legal-service-index shadow-box">
    <div class = "row">
        <div class = "col-xs-12 tables">
            <h2 class="title"><?= Html::encode($this->title) ?></h2>
            <div class="col-xs-12">
                <?php // echo $this->render('_search', ['model' => $searchModel]);  ?>
                <br>
                <p>
                    <?= Html::a(Yii::t('LegalService', 'Create Legal Service'), ['create'], ['class' => 'btn btn-success']) ?>
                </p>
                <?php Pjax::begin(['id' => 'legal-service']); ?>    
                <?=
                GridView::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => [
                        ['class' => 'yii\grid\SerialColumn'],
                      //  'id',
                        [
                            'attribute' => 'number', 
                            'headerOptions' => [ 'width' => '50' ], 
                            'contentOptions' => [ 'style' => 'text-align: center' ]
                        ],
                        [
                            'attribute' => 'data_time',
                            'format' => ['date', 'php:d.m.Y'],
                            'headerOptions' => [ 'width' => '130' ],
                            'contentOptions' => [ 'style' => 'text-align: center' ]
                        ], 
                        //'number',
                        //'data_time',
                        'event',
                        'result',
                        ['class' => 'yii\grid\ActionColumn','template'=>'{update} {delete}' ],
                    ],
                    'tableOptions' => [
                        'class' => 'sTables table'
                    ],
                ]);
                ?>
                <?php Pjax::end(); ?>
            </div>
        </div>
    </div>
</div>

views/legal-service/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\LegalService */

$this->title = Yii::t('LegalService', 'Update Record', [
    'modelClass' => 'Legal Service',
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('LegalService', 'Legal Services'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('LegalService', 'Update');
?>
<div class="legal-service-update">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/legal-service/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\LegalService */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('LegalService', 'Legal Services'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="legal-service-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('LegalService', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('LegalService', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('LegalService', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
         //   'id',
            'number',
            'data_time',
            'event',
            'result',
        ],
    ]) ?>

</div>