modules/procedures/models/Procedures.php
<?php

namespace app\modules\procedures\models;

use Yii;
use app\models\TblOrganizations;
use budyaga\users\models\User;
use app\modules\procedures\models\ProcedureTypes;
use yii\helpers\ArrayHelper;
use app\models\TblOrganizationsMethods;

/**
 * This is the model class for table "procedures".
 *
 * @property integer $id
 * @property integer $organization_id
 * @property integer $type_id
 * @property string $case_number
 * @property integer $court_id
 * @property integer $judge_id
 * @property string $create_date
 * @property string $results_session_date
 * @property string $close_date
 * @property string $status
 * @property integer $manager_id
 * @property string $introduction_basis
 * @property string $approval_basis
 * @property string $judgment_date
 * @property string $recept_application_date
 * @property integer $applicant_id
 * @property string $manager_approval_date
 * @property integer $last_seen
 *
 * @property TblOrganizations $applicant
 * @property TblOrganizations $court
 * @property TblOrganizations $judge
 * @property TblOrganizations $manager
 * @property TblOrganizations $organization
 * @property ProcedureTypes $type
 */
class Procedures extends \yii\db\ActiveRecord
{
    public $name;
    public $court;
    public $judge;
    public $manager;
    public $applicant;

    const SCENARIO_ARCHIVE = 'archive';
    const SCENARIO_DEFAULT = 'default';

    /**
     * @var array|null
     */
    private $_params;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'procedures';
    }

    public function scenarios()
    {
        return [
            self::SCENARIO_ARCHIVE => [],
            self::SCENARIO_DEFAULT => ['id', 'organization_id', 'type_id',
                    'case_number',
                    'court_id',
                    'judge_id',
                    'create_date',
                    'results_session_date',
                    'close_date',
                    'status',
                    'manager_id',
                    'introduction_basis',
                    'approval_basis',
                    'judgment_date',
                    'recept_application_date',
                    'applicant_id',
                    'manager_approval_date',
                    'last_seen',]
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['organization_id', 'type_id', 'case_number', 'court_id', 'judge_id', 'create_date', 'manager_id'], 'required'],
            [['organization_id', 'type_id', 'court_id', 'judge_id', 'manager_id', 'applicant_id', 'last_seen'], 'integer'],
            [['create_date', 'results_session_date', 'close_date', 'judgment_date', 'recept_application_date', 'manager_approval_date'], 'safe'],
            [['status', 'introduction_basis', 'approval_basis'], 'string'],
            [['case_number'], 'string', 'max' => 14],
            //['case_number', 'match', 'pattern'=>'/[a-zA-Zа-яА-Я]\d{2}-\d{5}\/\d{4}/u'],
            [['applicant_id'], 'exist', 'skipOnError' => true, 'targetClass' => TblOrganizations::className(), 'targetAttribute' => ['applicant_id' => 'id']],
            [['court_id'], 'exist', 'skipOnError' => true, 'targetClass' => TblOrganizations::className(), 'targetAttribute' => ['court_id' => 'id']],
            [['judge_id'], 'exist', 'skipOnError' => true, 'targetClass' => TblOrganizations::className(), 'targetAttribute' => ['judge_id' => 'id']],
            [['manager_id'], 'exist', 'skipOnError' => true, 'targetClass' => TblOrganizations::className(), 'targetAttribute' => ['manager_id' => 'id']],
            [['organization_id'], 'exist', 'skipOnError' => true, 'targetClass' => TblOrganizations::className(), 'targetAttribute' => ['organization_id' => 'id']],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => ProcedureTypes::className(), 'targetAttribute' => ['type_id' => 'id']],
            [['type_id'], 'in', 'range' => array_keys( $this->getProcedureTypeList() )],

            [['name', 'court', 'judge', 'manager', 'manager_approval_date'], 'required'],
            
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'organization_id' => Yii::t('app', 'Organization ID'),
            'type_id' => Yii::t('procedures', 'TYPE_ID'),
            'case_number' => Yii::t('procedures', 'CASE_NUMBER'),
            'court_id' => Yii::t('procedures', 'COURT'),
            'judge_id' => Yii::t('procedures', 'JUDGE'),
            'create_date' => Yii::t('procedures', 'CREATE_DATE'),
            'results_session_date' => Yii::t('procedures', 'RESULTS_SESSION_DATE'),
            'close_date' => Yii::t('procedures', 'CLOSE_DATE'),
            'status' => Yii::t('app', 'Status'),
            'manager_id' => Yii::t('procedure', 'MANAGER'),
            'introduction_basis' => Yii::t('procedures', 'INTRODUCTION_BASIS'),
            'approval_basis' => Yii::t('procedures', 'APPROVAL_BASIS'),
            'judgment_date' => Yii::t('procedures', 'JUDGMENT_DATE'),
            'recept_application_date' => Yii::t('procedures', 'RECEPT_APPLICATION_DATE'),
            'applicant_id' => Yii::t('app', 'Applicant ID'),
            'manager_approval_date' => Yii::t('procedures', 'MANAGER_APPROVAL_DATE'),
            'last_seen' => Yii::t('app', 'Last Seen'),

            'name' => Yii::t('procedures', 'NAME'),
            'court' => Yii::t('procedures', 'COURT'),
            'judge' => Yii::t('procedures', 'JUDGE'),
            'manager' => Yii::t('procedures', 'MANAGER'),
            'applicant' => Yii::t('procedures', 'APPLICANT'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApplicant()
    {
        return $this->hasOne(TblOrganizations::className(), ['id' => 'applicant_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCourt()
    {
        return $this->hasOne(TblOrganizations::className(), ['id' => 'court_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJudge()
    {
        return $this->hasOne(TblOrganizations::className(), ['id' => 'judge_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getManager()
    {
        return $this->hasOne(TblOrganizations::className(), ['id' => 'manager_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrganization()
    {
        return $this->hasOne(TblOrganizations::className(), ['id' => 'organization_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(ProcedureTypes::className(), ['id' => 'type_id']);
    }
    
    /**
    * get list of procedures type for dropdown
    */
    public static function getProcedureTypeList()
    {
        $droptions = ProcedureTypes::find()->asArray()->all();
        return ArrayHelper::map($droptions, 'id', 'type');
    }

    /**
     * @return array|null
     */
    public function getParams()
    {
        if ($this->_params === null) {
            $this->_params = TblOrganizationsMethods::getParams($this->organization_id);
        }

        return $this->_params;
    }

    /**
     * @return string
     */
    public function getName()
    {
        $name = '';
        $params = $this->getParams();

        if($params):
            foreach( $params as $param ):
                if( in_array( 'Название', $param ) ):
                    $name = $param['value'];
                    break;
                endif;    
            endforeach;    
        endif;    

        return $name;
    }

    /**
     * @return string|null
     */
    public function getShortName()
    {
        $params = $this->getParams();

        $shortNameLabel = 'Сокр. наименование';

        foreach ($params as $param) {
            if ($param['label'] === $shortNameLabel) {
                return $param['value'];
            }
        }

        return null;
    }

    public function getJudgeName()
    {
        $name = $lastname = $firstname = $patronymic = '';
        $params = [];

        if( $params = TblOrganizationsMethods::getParams($this->judge_id) ):

            foreach( $params as $param ):
                if( in_array( 'Фамилия', $param ) ) $lastname = $param['value'];
                if( in_array( 'Имя', $param ) ) $firstname = $param['value'];
                if( in_array( 'Отчество', $param ) ) $patronymic = $param['value'];
            endforeach; 
            
            $name = $lastname . ( $firstname ? ' ' . $firstname : '' ) . ( $patronymic ? ' ' . $patronymic : '' );
        endif;    

        return $name;
    }

    public function getCourtName()
    {
        $name = '';
        $params = [];

        if( $params = TblOrganizationsMethods::getParams($this->court_id) ):

             foreach( $params as $param ):
                if( in_array( 'Название', $param ) ):
                    $name = $param['value'];
                    break;
                endif;    
            endforeach; 
            
        endif;    

        return $name;
    }
    
    public function getEnumList($field)
    {
        $params = [ ':field' => $field ];
        $values = Yii::$app->db->createCommand("SHOW COLUMNS FROM procedures like :field", $params )->queryAll();
        if ($values) {
            $option_array = explode("','",preg_replace("/(enum|set)\('(.+?)'\)/","\\2", $values[0]['Type']));
        }
        //echo '<pre>'.print_r($values,true).'</pre>';
        //exit('<pre>'.print_r($option_array,true).'</pre>');
        return $option_array;
    }
    
    public function beforeValidate()
    {
        if ( isset($this->create_date) && !empty($this->create_date) ) {
            $new_date_format = date('Y-m-d', strtotime($this->create_date));

modules/procedures/views/default/_additional_properties.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\bootstrap\Modal;
use kartik\date\DatePicker;
use yii\widgets\Pjax;

// add module assets
use app\modules\procedures\assets\ProceduresAsset;
ProceduresAsset::register($this);
?>

<h4><?= Yii::t('procedures', 'ADDITIONAL_TITLE') ?></h4>

<?php Pjax::begin(['id' => 'additional-properties']); ?> 

    <?php $additional_form = ActiveForm::begin(['id' => 'additional-properties-form', 'action' => '/procedures/update-additional-properties']); ?>

    <input type="hidden" id="proceduresadditionalproperties-id" class="form-control" name="ProceduresAdditionalProperties[id]" value="<?= $additional_properties_model->id ?>">

    <?php echo $additional_form->field($additional_properties_model, 'name', [ 'options' => [ 'class' => 'col-lg-8 field-procedures' ] ])->textInput(['readonly' => 'readonly']) ?>

    <div class="form-group col-lg-4">
        <div class="form-group col-lg-4">
        <?php echo Html::button( Yii::t('procedures', 'CHOOSE'), ['class' => 'btn btn-primary choose-contractor-btn', 'data-toggle' => 'modal', 'data-target' => '#modalContractors', 'data-type' => 'choose_newspaper'] ); ?>
    </div>
    </div>
    <input type="hidden" id="proceduresadditionalproperties-np_id" class="form-control" name="ProceduresAdditionalProperties[np_id]" value="<?= $additional_properties_model->np_id ?>">
    <div class="clearfix"></div> 
    
    <?= $additional_form->field($additional_properties_model, 'np_date', ['options' => ['class' => 'col-lg-2 form-group field-procedures-first']])
                    ->widget(DatePicker::classname(), [
                        'options' => ['value' => ( $additional_properties_model->np_date ? Yii::$app->formatter->asDate( $additional_properties_model->np_date, 'php:d.m.Y') : '')],
                        'removeButton' => false,
                        'pluginOptions' => [
                            'autoclose'=>true,
                            'format' => 'dd.mm.yyyy'
                        ]
                    ]); ?>
    
    <?= $additional_form->field($additional_properties_model, 'np_number', ['options' => ['class' => 'col-lg-2 form-group']])->textInput(); ?>
    
    <?= $additional_form->field($additional_properties_model, 'np_page_number', ['options' => ['class' => 'col-lg-2 form-group']])->textInput(); ?>
    
    <?= $additional_form->field($additional_properties_model, 'np_post_number', ['options' => ['class' => 'col-lg-2 form-group']])->textInput(); ?>
    
    <div class="clearfix"></div>
    
    <?= $additional_form->field($additional_properties_model, 'efrsb_date', ['options' => ['class' => 'col-lg-2 form-group field-procedures-first']])
                    ->widget(DatePicker::classname(), [
                        'options' => ['value' => ( $additional_properties_model->efrsb_date ? Yii::$app->formatter->asDate( $additional_properties_model->efrsb_date, 'php:d.m.Y') : '')],
                        'removeButton' => false,
                        'pluginOptions' => [
                            'autoclose'=>true,
                            'format' => 'dd.mm.yyyy'
                        ]
                    ]); ?>
    
    <?= $additional_form->field($additional_properties_model, 'efrsb_post_number', ['options' => ['class' => 'col-lg-2 form-group']])->textInput(); ?>
    
    <?= $additional_form->field($additional_properties_model, 'reg_credit_close_date', ['options' => ['class' => 'col-lg-2 form-group']])
                    ->widget(DatePicker::classname(), [
                        'options' => ['value' => ( $additional_properties_model->reg_credit_close_date ? Yii::$app->formatter->asDate( $additional_properties_model->reg_credit_close_date, 'php:d.m.Y') : '')],
                        'removeButton' => false,
                        'pluginOptions' => [
                            'autoclose'=>true,
                            'format' => 'dd.mm.yyyy'
                        ]
                    ]); ?>
    <div class="clearfix"></div>
    
    <?= $additional_form->field($additional_properties_model, 'property_inventory', ['options' => ['class' => 'col-lg-8 form-group']])->textInput(); ?>
    
    <?= $additional_form->field($additional_properties_model, 'property_assessment', ['options' => ['class' => 'col-lg-8 form-group']])->textInput(); ?>
    <div class="clearfix"></div>
    
    <h5><?= Yii::t('procedures', 'ADDITIONAL_ENSURANCE_AGREEMENT') ?></h5>
    
    <?= $additional_form->field($additional_properties_model, 'insurance_company_name', ['options' => ['class' => 'col-lg-8 form-group']])->textInput(); ?>
    
    <?= $additional_form->field($additional_properties_model, 'insurance_register_data', ['options' => ['class' => 'col-lg-8 form-group']])->textInput(); ?>
    
    <?= $additional_form->field($additional_properties_model, 'proc_introduction_background', ['options' => ['class' => 'col-lg-8 form-group']])->textarea(['rows' => '6']); ?>
    
    <?= $additional_form->field($additional_properties_model, 'proc_introduction_reason', ['options' => ['class' => 'col-lg-8 form-group']])->textarea(['rows' => '6']); ?>
    <div class="clearfix"></div>
    
    <div class="form-group col-lg-8">

        <div class=" pull-right">
            <?= Html::submitButton(Yii::t('procedures', 'SAVE'), ['class' => 'btn btn-primary', 'id' => 'proc-additional-prop-submit', 'data-property' => 'additional']) ?>
            <?= Html::resetButton(Yii::t('procedures', 'RESET'), ['class' => 'btn btn-default', 'id' => 'proc-additional-prop-reset', 'data-property' => 'additional']) ?>
        </div>
    </div>
    
    

    <?php ActiveForm::end(); ?>
    
<?php Pjax::end(); ?>

modules/procedures/views/default/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\bootstrap\Modal;
use kartik\date\DatePicker;
use yii\widgets\MaskedInput ;

/* @var $this yii\web\View */
/* @var $model app\modules\procedures\models\Procedures */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="procedures-form">

    <?php $form = ActiveForm::begin(['id' => 'create-procedure']); ?>

    <?php //echo $form->field($model, 'organization_id')->label('')->hiddenInput() ?>
    <input type="hidden" id="procedures-organization_id" class="form-control" name="Procedures[organization_id]" value="">

    <?php echo $form->field($model, 'name', [ 'options' => [ 'class' => 'col-lg-8 field-procedures' ] ])->textInput(['readonly' => 'readonly']) ?>

    <!--div class="form-group col-lg-8 field-procedures">
        <label class="control-label" for="procedures-name"><?= Yii::t('procedures', 'NAME'); ?></label>
        <input type="text" id="procedures-name" class="form-control" readonly="readonly" required="required">
    </div-->

    <div class="form-group col-lg-4">
        <?php echo Html::button( Yii::t('procedures', 'CHOOSE'), ['class' => 'btn btn-primary choose-contractor-btn', 'data-toggle' => 'modal', 'data-target' => '#modalContractors', 'data-type' => 'choose_pd'] ); ?>
    </div>

    <div class="form-group col-lg-5 field-procedures">
        <label class="control-label" for="procedures-inn"><?= Yii::t('procedures', 'INN'); ?></label>
        <input type="text" id="procedures-inn" class="form-control" readonly="readonly">
    </div>    
    <div class="clearfix"></div>

    <?= $form->field($model, 'type_id', ['options' => ['class' => 'col-lg-5 form-group field-procedures']])->dropDownList($model->procedureTypeList, ['prompt' => Yii::t('procedures', 'CHOOSE_ONE')]); ?>

    <?= $form->field($model, 'case_number', ['options' => ['class' => 'col-lg-2 col-lg-offset-1 form-group field-procedures']])
            ->textInput(['maxlength' => 14]); //widget(MaskedInput::className(), [ 'mask' => 'a99-99999/9999', ]); //textInput(['maxlength' => true]) ?>
    <div class="clearfix"></div>


    <?php echo $form->field($model, 'court', [ 'options' => [ 'class' => 'col-lg-8 field-procedures' ] ])->textInput(['readonly' => 'readonly']) ?>

    <div class="form-group col-lg-4">
        <?php echo Html::button( Yii::t('procedures', 'CHOOSE'), ['class' => 'btn btn-primary choose-contractor-btn', 'data-toggle' => 'modal', 'data-target' => '#modalContractors', 'data-type' => 'choose_court'] ); ?>
    </div>
    <input type="hidden" id="procedures-court_id" class="form-control" name="Procedures[court_id]"  value="">
    <div class="clearfix"></div>

    <?php echo $form->field($model, 'judge', [ 'options' => [ 'class' => 'col-lg-8 field-procedures' ] ])->textInput(['readonly' => 'readonly']) ?>

    <div class="form-group col-lg-4">
        <?php echo Html::button( Yii::t('procedures', 'CHOOSE'), ['class' => 'btn btn-primary choose-contractor-btn', 'data-toggle' => 'modal', 'data-target' => '#modalContractors', 'data-type' => 'choose_judge'] ); ?>
    </div>
    <input type="hidden" id="procedures-judge_id" class="form-control" name="Procedures[judge_id]" value="">
    <div class="clearfix"></div>
    

    <?= $form->field($model, 'create_date', ['options' => ['class' => 'col-lg-3 form-group ']])->widget(DatePicker::classname(), [
        'options' => ['value' => date('d.m.Y')],
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'dd.mm.yyyy'
        ]
    ]); ?>
    <?= $form->field($model, 'results_session_date', ['options' => ['class' => 'col-lg-3 form-group']])->widget(DatePicker::classname(), [
        'options' => [],
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'dd.mm.yyyy'
        ]
    ]); ?>
    <?= $form->field($model, 'close_date', ['options' => ['class' => 'col-lg-3 form-group']])->widget(DatePicker::classname(), [
        'options' => [],
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'dd.mm.yyyy'
        ]
    ]); ?>
    <div class="clearfix"></div>
    
    <?php echo $form->field($model, 'manager', [ 'options' => [ 'class' => 'col-lg-8 field-procedures' ] ])->textInput(['readonly' => 'readonly']) ?>

    <div class="form-group col-lg-4">
        <?php echo Html::button( Yii::t('procedures', 'CHOOSE'), ['class' => 'btn btn-primary choose-contractor-btn', 'data-toggle' => 'modal', 'data-target' => '#modalContractors', 'data-type' => 'choose_manager'] ); ?>
    </div>
    <input type="hidden" id="procedures-manager_id" class="form-control" name="Procedures[manager_id]">
    <div class="clearfix"></div>
    
    <input type="hidden" id="procedures-applicant_id" class="form-control" name="Procedures[applicant_id]">
    

    
    <?php //echo $form->field($model, 'introduction_basis')->dropDownList([ 'Определение' => 'Определение', 'Решение' => 'Решение', ], ['prompt' => '']) ?>

    <?php //echo $form->field($model, 'approval_basis')->dropDownList([ 'Вышеупомянутое' => 'Вышеупомянутое', 'Определение' => 'Определение', ], ['prompt' => '']) ?>

    <?php //echo $form->field($model, 'judgment_date')->textInput() ?>

    <?php //echo $form->field($model, 'recept_application_date')->textInput() ?>

    <?php //echo  $form->field($model, 'applicant_id')->textInput() ?>

    <?php //echo $form->field($model, 'manager_approval_date')->textInput() ?>

    <input type="hidden" id="procedures-manager_approval_date" class="form-control" name="Procedures[manager_approval_date]" value="<?= date('d.m.Y') ?>">
    <input type="hidden" id="procedures-judgment_date" class="form-control" name="Procedures[judgment_date]" value="<?= date('d.m.Y') ?>">

    <?php //echo $form->field($model, 'last_seen')->textInput() ?>

    <?php //echo $form->field($model, 'id')->label('')->hiddenInput() ?>
    <input type="hidden" id="procedures-id" class="form-control" name="Procedures[id]">

    <div class="form-group">
        
        <?= Html::submitButton($model->isNewRecord ? Yii::t('procedures', 'CREATE') : Yii::t('procedures', 'UPDATE'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php
Modal::begin([
    'header' => '<h3>' . Yii::t('procedures', 'CONTRACTORS') . '</h3>',
    'headerOptions' => ['id' => 'modalContractorsHeader'],
    'id' => 'modalContractors',
    'size' => 'modal-md',
    //keeps from closing modal with esc key or by clicking out of the modal.
    // user must click cancel or X to close
    'clientOptions' => ['backdrop' => 'static', 'keyboard' => FALSE, ],
    ]
);

//echo $this->render('/default/contractor-search-form', ['model' => $search_model, 'contractor_types' => $contractor_types]);
?>

<form id="contractors-list-form" data-type=""></form>

<?php
Modal::end();
?>

<?php
Modal::begin([
    'header' => '<h3>' . Yii::t('procedures', 'MANAGERS') . '</h3>',
    'headerOptions' => ['id' => 'modalManagersHeader'],
    'id' => 'modalManagers',
    'size' => 'modal-md',
    //keeps from closing modal with esc key or by clicking out of the modal.
    // user must click cancel or X to close
    'clientOptions' => ['backdrop' => 'static', 'keyboard' => FALSE, ],
    ]
);

echo $this->render('/default/manager-search-form', ['model' => $manager_search_model, 'contractor_types' => $contractor_types]);
?>

<form id="managers-list-form" data-type=""></form>

<?php
Modal::end();
?>

modules/procedures/views/default/_save_dialog.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>
<div class="save-dialog">
    <h4><?= Yii::t('procedures', 'SAVE_QUESTION') ?></h4>
    <h5><?= Yii::t('procedures', 'USER') . Yii::$app->user->identity->getNameFIO(); ?></h5>
    <div class="form-group">
        <div class=" pull-right">
            <?= Html::submitButton(Yii::t('procedures', 'SAVE'), ['class' => 'btn btn-primary', 'id' => 'proc-confirm-submit', 'data-property' => '']) ?>
            <?= Html::resetButton(Yii::t('procedures', 'CANCEL'), ['class' => 'btn btn-default', 'id' => 'proc-confirm-cancel']) ?>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

modules/procedures/views/default/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\procedures\models\ProceduresSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="procedures-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'organization_id') ?>

    <?= $form->field($model, 'type_id') ?>

    <?= $form->field($model, 'case_number') ?>

    <?= $form->field($model, 'court_id') ?>

    <?php // echo $form->field($model, 'judge_id') ?>

    <?php // echo $form->field($model, 'create_date') ?>

    <?php // echo $form->field($model, 'results_session_date') ?>

    <?php // echo $form->field($model, 'close_date') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'manager_id') ?>

    <?php // echo $form->field($model, 'introduction_basis') ?>

    <?php // echo $form->field($model, 'approval_basis') ?>

    <?php // echo $form->field($model, 'judgment_date') ?>

    <?php // echo $form->field($model, 'recept_application_date') ?>

    <?php // echo $form->field($model, 'applicant_id') ?>

    <?php // echo $form->field($model, 'manager_approval_date') ?>

    <?php // echo $form->field($model, 'last_seen') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('procedures', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('procedures', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/procedures/views/default/contractor-search-form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<div class="contractors-form">
	<?php $form = ActiveForm::begin(['id' => 'contractor-search-form', 'action' => '/procedures/default/search-contractor']); ?>
		<?= $form->field($model, 'search', ['options' => ['class' => 'col-lg-8 form-group field-procedures']])->label(Yii::t('procedures', 'SEARCH'))->textInput() ?>
		<div class="form-group col-lg-4">
	        <?= Html::submitButton(Yii::t('procedures', 'SEARCH'), ['class' => 'btn btn-primary', 'id' => 'search-contractors-btn']) ?>
	    </div>
	    <div class="clearfix"></div>
		<?= $form->field($model, 'type')->label(Yii::t('procedures', 'CONTRACTOR_TYPE'))
                        ->dropDownList($contractor_types /*, ['prompt' => Yii::t('procedures', 'CHOOSE_ONE')]*/); ?>
	<?php ActiveForm::end(); ?>
</div>

modules/procedures/views/default/index.php
<div class="Procedures-default-index">
    <h1><?= $this->context->action->uniqueId ?></h1>
    <!--pre>
        <?= print_r($orgs, true) ?>
    </pre>
    
    <pre>
        <?= print_r($org_details, true) ?>
    </pre>

    <pre>
        <?= print_r($params, true) ?>
    </pre-->
</div>